// SPDX-FileCopyrightText: 2026 Sebastien Rousseau <sebastian.rousseau@gmail.com>
// SPDX-License-Identifier: Apache-2.0

//go:build ignore

// specgen writes the published JSON Schemas — the MCP and A2A evaluation
// attestations and the security graph — from the Go types that implement
// them, and with -check fails when a committed file has drifted.
//
// A hand-written schema beside the Go types would be a second copy that
// disagrees the first time a field is added, so each schema is derived from
// its root type by reflection. The scoring rubric is not here: it is
// generated from passmcp's scorer, in passmcp, because the scorer is the thing it
// must never disagree with.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"time"

	"satellion.com/passmcp-reporting/a2a"
	"satellion.com/passmcp-reporting/attestation"
	"satellion.com/passmcp-reporting/graph"
)

// comment travels in each file, because JSON has no other place for it.
const comment = "Generated by scripts/specgen from the passmcp-reporting source; do not edit. " +
	"Licensed Apache-2.0 (see REUSE.toml)."

// document is one published schema: where it goes, what it is called, the
// root type it describes and the fields whose value is a constant or an
// enumeration rather than any string.
type document struct {
	path, id, title string
	root            reflect.Type
	fixed           map[string]map[string]any
}

var verdictStatus = map[string]any{"type": "string", "enum": []string{"pass", "warn", "fail", "skip", "info"}}

var documents = []document{
	{
		path:  "spec/attestation/mcp-evaluation-v1.schema.json",
		id:    attestation.PredicateType + "/schema.json",
		title: "passmcp MCP evaluation attestation (in-toto Statement, predicate v1)",
		root:  reflect.TypeOf(attestation.Statement{}),
		// fixed overrides the reflected schema for the fields whose value is a
		// constant or an enumeration. Reflection sees a string; the format
		// sees a fixed URI or a closed set, and a consumer validating against
		// the schema should be told, so the schema says what a valid statement
		// must carry rather than only its shape.
		fixed: map[string]map[string]any{
			"Statement":  {"_type": map[string]any{"const": attestation.StatementType}, "predicateType": map[string]any{"const": attestation.PredicateType}},
			"Evaluation": {"subjectKind": map[string]any{"const": attestation.SubjectKindDescriptor}},
			"Target":     {"transport": map[string]any{"type": "string", "enum": []string{"http", "stdio"}}},
			"Verdict":    {"status": verdictStatus},
		},
	},
	{
		path:  "spec/attestation/a2a-evaluation-v1.schema.json",
		id:    a2a.PredicateType + "/schema.json",
		title: "passmcp A2A evaluation attestation (in-toto Statement, predicate v1)",
		root:  reflect.TypeOf(a2a.Statement{}),
		fixed: map[string]map[string]any{
			"Statement":  {"_type": map[string]any{"const": attestation.StatementType}, "predicateType": map[string]any{"const": a2a.PredicateType}},
			"Evaluation": {"subjectKind": map[string]any{"const": a2a.SubjectKindDescriptor}},
			"Target":     {"transport": map[string]any{"type": "string", "enum": []string{"https", "http"}}},
			"Verdict":    {"status": verdictStatus},
		},
	},
	{
		path:  "spec/graph/graph-v1.schema.json",
		id:    graph.Version + "/schema.json",
		title: "passmcp security graph (v1)",
		root:  reflect.TypeOf(graph.Graph{}),
		fixed: map[string]map[string]any{
			"Graph": {"version": map[string]any{"const": graph.Version}},
			"Node": {"kind": map[string]any{"type": "string", "enum": []graph.Kind{
				graph.KindAgent, graph.KindServer, graph.KindTool, graph.KindIdentity, graph.KindSource, graph.KindAttestation}}},
			"Edge": {"kind": map[string]any{"type": "string", "enum": []graph.EdgeKind{
				graph.Uses, graph.Exposes, graph.Authorizes, graph.DiscoveredBy, graph.AttestedBy}}},
			"ServerProps": {"transport": map[string]any{"type": "string", "enum": []string{"http", "stdio"}}},
			"SourceProps": {"type": map[string]any{"type": "string", "enum": []string{"config", "gateway", "registry", "targets"}}},
		},
	},
}

func main() {
	verify := len(os.Args) > 1 && os.Args[1] == "-check"
	stale := false
	for _, d := range documents {
		want, err := render(d.schema())
		if err != nil {
			fail(err)
		}
		if verify {
			got, err := os.ReadFile(d.path)
			if err != nil || !bytes.Equal(got, want) {
				fmt.Fprintf(os.Stderr, "specgen: %s out of date with the source; run make spec\n", d.path)
				stale = true
			}
			continue
		}
		if err := os.MkdirAll(filepath.Dir(d.path), 0o755); err != nil { // #nosec G301 -- a docs directory
			fail(err)
		}
		if err := os.WriteFile(d.path, want, 0o644); err != nil { // #nosec G306 -- a published file
			fail(err)
		}
		fmt.Printf("specgen: wrote %s\n", d.path)
	}
	if stale {
		os.Exit(1)
	}
	if verify {
		fmt.Println("specgen: every published schema matches the source")
	}
}

// render is deterministic: encoding/json sorts map keys, and the trailing
// newline makes the file a well-formed text file for every tool that cares.
func render(v any) ([]byte, error) {
	b, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(b, '\n'), nil
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "specgen:", err)
	os.Exit(1)
}

// schema describes the document's root type as JSON Schema 2020-12.
func (d document) schema() any {
	defs := map[string]any{}
	r := typeSchema(d.root, d.fixed, defs)
	return map[string]any{
		"$schema":  "https://json-schema.org/draft/2020-12/schema",
		"$id":      d.id,
		"$comment": comment,
		"title":    d.title,
		"$ref":     r["$ref"],
		"$defs":    defs,
	}
}

var timeType = reflect.TypeOf(time.Time{})

func typeSchema(t reflect.Type, fixed map[string]map[string]any, defs map[string]any) map[string]any {
	for t.Kind() == reflect.Pointer {
		t = t.Elem()
	}
	if t == timeType {
		return map[string]any{"type": "string", "format": "date-time"}
	}
	switch t.Kind() {
	case reflect.String:
		return map[string]any{"type": "string"}
	case reflect.Bool:
		return map[string]any{"type": "boolean"}
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		return map[string]any{"type": "integer"}
	case reflect.Float32, reflect.Float64:
		return map[string]any{"type": "number"}
	case reflect.Slice, reflect.Array:
		return map[string]any{"type": "array", "items": typeSchema(t.Elem(), fixed, defs)}
	case reflect.Map:
		return map[string]any{"type": "object", "additionalProperties": typeSchema(t.Elem(), fixed, defs)}
	case reflect.Struct:
		name := t.Name()
		if _, done := defs[name]; !done {
			defs[name] = nil // reserve, so a recursive type terminates
			props := map[string]any{}
			var required []string
			for i := 0; i < t.NumField(); i++ {
				f := t.Field(i)
				if !f.IsExported() {
					continue
				}
				tag := f.Tag.Get("json")
				jname, opts, _ := strings.Cut(tag, ",")
				if jname == "-" {
					continue
				}
				if jname == "" {
					jname = f.Name
				}
				if v, ok := fixed[name][jname]; ok {
					props[jname] = v
				} else {
					props[jname] = typeSchema(f.Type, fixed, defs)
				}
				if !strings.Contains(opts, "omitempty") {
					required = append(required, jname)
				}
			}
			def := map[string]any{"type": "object", "properties": props}
			if len(required) > 0 {
				def["required"] = required
			}
			defs[name] = def
		}
		return map[string]any{"$ref": "#/$defs/" + name}
	}
	fail(fmt.Errorf("no schema mapping for %s", t))
	return nil
}
