#!/usr/bin/env bats
# SPDX-FileCopyrightText: 2026 Sebastien Rousseau <sebastian.rousseau@gmail.com>
# SPDX-License-Identifier: Apache-2.0
#
# scripts/complexity.sh: the complexity ceilings against a baseline that
# may only shrink. golangci-lint is a stub that prints LINT_JSON and exits
# LINT_RC, so each case states exactly what the linter measured.

load helpers

setup() {
  sandbox complexity.sh
  export GOLANGCI_LINT=${STUBS}/golangci-lint
  stub golangci-lint <<'STUB'
printf '%s' "${LINT_JSON:-{\"Issues\":[]}}"
exit "${LINT_RC:-0}"
STUB
  : >"${SANDBOX}/scripts/complexity-baseline.txt"
}

# issue prints one golangci-lint issue from linter $1 in file $2 with text $3.
issue() {
  printf '{"FromLinter":"%s","Pos":{"Filename":"%s"},"Text":"%s"}' "$1" "$2" "$3"
}

# measured sets what the stub reports: the issues given as arguments.
measured() {
  local IFS=,
  export LINT_JSON="{\"Issues\":[$*]}" LINT_RC=1
}

cyclo() { issue gocyclo a/a.go "cyclomatic complexity $1 of func \`(*T).Validate\` is high (> 10)"; }

# baseline writes the baseline's entries, one per argument.
baseline() {
  printf '# header\n' >"${SANDBOX}/scripts/complexity-baseline.txt"
  printf '%s\n' "$@" >>"${SANDBOX}/scripts/complexity-baseline.txt"
}

check() {
  run "${SANDBOX}/scripts/complexity.sh" "$@"
}

@test "no offenders and an empty baseline pass" {
  check
  [ "${status}" -eq 0 ]
  [[ "${output}" == *"0 offenders, none new, none worse"* ]]
}

@test "an offender the baseline records at the same measure passes" {
  measured "$(cyclo 15)"
  baseline $'gocyclo\ta/a.go\t(*T).Validate\t15'
  check
  [ "${status}" -eq 0 ]
  [[ "${output}" == *"1 offenders, none new, none worse"* ]]
}

@test "a new offender fails" {
  measured "$(cyclo 11)"
  check
  [ "${status}" -eq 1 ]
  [[ "${output}" == *"new offender: a/a.go (*T).Validate: gocyclo 11"* ]]
}

@test "a baseline entry that got worse fails" {
  measured "$(cyclo 16)"
  baseline $'gocyclo\ta/a.go\t(*T).Validate\t15'
  check
  [ "${status}" -eq 1 ]
  [[ "${output}" == *"worse: a/a.go (*T).Validate: gocyclo 15 -> 16"* ]]
}

@test "a baseline entry now within the ceiling but not removed fails" {
  baseline $'gocyclo\ta/a.go\t(*T).Validate\t15'
  check
  [ "${status}" -eq 1 ]
  [[ "${output}" == *"now within the ceiling but still in the baseline: a/a.go (*T).Validate"* ]]
}

@test "a baseline entry that improved but was not recorded fails" {
  measured "$(cyclo 12)"
  baseline $'gocyclo\ta/a.go\t(*T).Validate\t15'
  check
  [ "${status}" -eq 1 ]
  [[ "${output}" == *"improved but not recorded: a/a.go (*T).Validate: gocyclo 15 -> 12"* ]]
}

@test "--update records an improvement, and the check then passes" {
  measured "$(cyclo 12)"
  baseline $'gocyclo\ta/a.go\t(*T).Validate\t15' $'gocognit\tb/b.go\tf\t20'
  check --update
  [ "${status}" -eq 0 ]
  grep -q $'^gocyclo\ta/a.go\t(\\*T).Validate\t12$' "${SANDBOX}/scripts/complexity-baseline.txt"
  run grep -q 'b/b.go' "${SANDBOX}/scripts/complexity-baseline.txt"
  [ "${status}" -ne 0 ]
  check
  [ "${status}" -eq 0 ]
}

@test "--update refuses to record a new or worse offender" {
  measured "$(cyclo 16)" "$(issue gocognit b/b.go "cognitive complexity 16 of func \`f\` is high (> 15)")"
  baseline $'gocyclo\ta/a.go\t(*T).Validate\t15'
  before=$(cat "${SANDBOX}/scripts/complexity-baseline.txt")
  check --update
  [ "${status}" -eq 1 ]
  [[ "${output}" == *"refusing to record a new or worse offender"* ]]
  [ "$(cat "${SANDBOX}/scripts/complexity-baseline.txt")" = "${before}" ]
}

@test "funlen's two measures are read and kept apart" {
  measured "$(issue funlen c/c.go "Function 'long' is too long (67 > 60)")" \
    "$(issue funlen c/c.go "Function 'busy' has too many statements (51 > 50)")"
  check
  [ "${status}" -eq 1 ]
  [[ "${output}" == *"new offender: c/c.go long: funlen-lines 67"* ]]
  [[ "${output}" == *"new offender: c/c.go busy: funlen-statements 51"* ]]
}

@test "a linter message the script cannot read fails rather than vanishing" {
  measured "$(issue gocyclo a/a.go 'something new about func Validate')"
  check
  [ "${status}" -eq 1 ]
  [[ "${output}" == *"a linter message this script cannot read"* ]]
}

@test "golangci-lint failing to run fails the check" {
  export LINT_JSON='' LINT_RC=3
  check
  [ "${status}" -eq 1 ]
  [[ "${output}" == *"golangci-lint failed in . (exit 3)"* ]]
}

@test "a hand-written Go file over 500 lines is an offender; a generated one is not" {
  seq 501 | sed 's|^|// |' >"${SANDBOX}/big.go"
  { echo '// Code generated by protoc-gen-go. DO NOT EDIT.'; seq 600 | sed 's|^|// |'; } >"${SANDBOX}/gen.go"
  seq 500 | sed 's|^|// |' >"${SANDBOX}/edge.go"
  check
  [ "${status}" -eq 1 ]
  [[ "${output}" == *"new offender: big.go -: file-lines 501"* ]]
  [[ "${output}" != *"gen.go"* ]]
  [[ "${output}" != *"edge.go"* ]]
}
